# arity
cc_library(
    name = "arity",
    srcs = ["arity.c"],
    hdrs = ["arity.h"],
    deps = [

    ],
    visibility = [
        "//visibility:public"
    ]
)

cc_test(
    name = "arity_test",
    size = "small",
    srcs = ["arity_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        ":arity"
    ],
)

# truth
cc_library(
    name = "truth",
    srcs = ["truth.c"],
    hdrs = ["truth.h"],
    deps = [

    ],
    visibility = [
        "//visibility:public"
    ]
)

cc_test(
    name = "truth_test",
    size = "small",
    srcs = ["truth_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        ":truth"
    ],
)
