load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/fd36851c8d383a2b711905eb488692da1152a3d8.zip"],
  strip_prefix = "googletest-fd36851c8d383a2b711905eb488692da1152a3d8",
)